---
title: "Figure Formatting GTE"
date: 2023-06-28
author: Samantha Yuen
output:
  html_document:
    toc: yes
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./figs-gte/"
    )
  })
editor_options:
  chunk_output_type: inline
---

**Goal**: Optimizing formatting of figures for my thesis

## Load Libraries

```{r}
set.seed(100)

library(ggplot2)
library(SeuratObject)
library(Seurat)

library(dplyr)

library(conflicted)
conflict_prefer("select", "dplyr") ## required in %>% dplyr

print(getwd())
size = 5

samplePalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", "#ff716e", "#999999", 
               "#0072B2", "#194c76", "#D55E00")
  # SF11159, SF11209, SF11215, SF11232, SF11247, SF11285, 
  # SRR10353960, SRR10353961, SRR10353962

gbmPaletteGTE <- c("#FF6B6B", "#56B4E9", "#80DB84",  # CL, MES, PN,
                   "#985F99", "#F4EC7B",  "#1CB086", "#A5B6AD") # CL-MES, CL-PN, MES-PN, NA
gbmsubtypes <- c("Classical", "Mesenchymal", "Proneural", 
                 "Classical-Mesenchymal", "Classical-Proneural", "Mesenchymal-Proneural", "NA")
gbmsubtypes_labels <- c("CL", "MES", "PN", "CL-MES", "CL-PN", "MES-PN", "NA")


celltypePalette <- c("#E69F00", "#ff716e", "#CC79A7", "#56B4E9", "#009E73", "#0072B2", "#F0E442", "#A5B6AD")
celltypes <- c(
  "Astrocyte",
  "OPC",
  "Diff. Oligodendrocytes",
  "Microglia",
  "Proliferating",
  "Endothelial",
  "T-cell",
  "Intermediate")
```

## Load Data

```{r Load-GTE}
data <- readRDS("D:\\backup files\\2021-11-11\\Cluster\\scratch\\gete-gbm\\results\\GBM-GSC neuroblastoma TE\\2021-09-02\\gte_gbmscIntUmap-subtypes.rds")
print(head(DefaultAssay(data)))
DefaultAssay(data) <- "integrated"
# DefaultAssay(data) <- "RNA"

colnames(data@meta.data)
```

## Quality Control figures

```{r}
# Cell Count (Bar)
p <- data@meta.data %>%
    ggplot(aes(x=sampleCombined, fill=sampleCombined)) + 
    labs(fill="Samples") + labs(x = "", y = "Cell Count") +
    scale_fill_manual(values = samplePalette) +
    # scale_x_discrete(labels = sampleCombined) +
    # scale_fill_discrete(labels = sampleCombined) +
    geom_bar() +
    theme_classic() +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), axis.text = element_text(size=10))
p
ggsave("fig_gte_cellcount-bar.tiff", plot = p, units="in", width=size*0.85, height=size*0.7, dpi=300, compression = 'lzw')



# PCA Elbow Plot
p <- ElbowPlot(data)
ggsave("fig_gte_elbowplot.tiff", plot = p, units="in", width=size*0.7, height=size*0.7, dpi=300, compression = 'lzw')

# Mito Ratio x Te Ratio

# Te Barplot

# Cell Count to csv
DefaultAssay(data) <- "RNA"
df <- data@meta.data %>% count(sampleCombined) 
df$genes.cell <- (dim(data)[1])/df$n
write.csv(df, file="gte_cellcounts.csv", row.names = F)

df <- data@meta.data %>% count(integrated_snn_res.0.3) 
write.csv(df, file="gte_cellcountscluster0.3.csv", row.names = F)

df <- data@meta.data %>% count(integrated_snn_res.0.4) 
write.csv(df, file="gte_cellcountscluster0.4.csv", row.names = F)

df <- data@meta.data %>% select(integrated_snn_res.0.3, gbm_subtype) %>% count(integrated_snn_res.0.3, gbm_subtype) 
write.csv(df, file="gte_cellcountssubtypes.csv", row.names = F)
```

## Cells per Cluster per Sample

```{r}
# PC20r03
DefaultAssay(data) <- "integrated"
df <- data@meta.data %>%
                group_by(sampleCombined) %>%
                count(integrated_snn_res.0.3)

df <- df %>% 
            group_by(integrated_snn_res.0.3) %>% 
            mutate(freq = (n / sum(n))*100) %>%
            mutate(rounded = round(freq, 2))
head(df)

p <- df %>% ggplot(aes(x=integrated_snn_res.0.3, y=rounded, fill=sampleCombined)) + 
        scale_fill_manual(values = samplePalette) +
        geom_bar( stat="identity", width = 0.9) + theme_classic() + 
        labs(y = "Cells per Cluster per Sample (%)", x = "hg38 + TE Mapped Cluster ID", fill= "Samples") +
        theme(axis.title = element_text(size=10), legend.position = "none")
ggsave("fig_gte_cellsxClusterxSamples_PC20r03.tiff", plot = p, units="in", width=size*0.6, height=size*0.6, dpi=300, compression = 'lzw')

# PC20r04
df <- data@meta.data %>%
                group_by(sampleCombined) %>%
                count(integrated_snn_res.0.4)

df <- df %>% 
            group_by(integrated_snn_res.0.4) %>% 
            mutate(freq = (n / sum(n))*100) %>%
            mutate(rounded = round(freq, 2))
head(df)


p <- df %>% ggplot(aes(x=integrated_snn_res.0.4, y=rounded, fill=sampleCombined)) + 
        scale_fill_manual(values = samplePalette) +
        geom_bar( stat="identity", width = 0.9) + theme_classic() + 
        labs(y = "Cells per Cluster per Sample (%)", x = "hg38 Mapped Cluster ID", fill= "Samples") +
        theme(axis.title = element_text(size=10), legend.position = "none")
ggsave("fig_gte_cellsxClusterxSamples_PC20r04.tiff", plot = p, units="in", width=size*0.6, height=size*0.6, dpi=300, compression = 'lzw')

# Celltype Ratio per Sample
```

## UMAPs

```{r}
# Clusters (resolution 0.3)
Idents(data) <- "integrated_snn_res.0.3"
DimPlot(data, label=TRUE) 
p <-DimPlot(data, label=FALSE) 
ggsave("fig_gte_PC20r03_UMAP.tiff", plot = p, units="in", width=size*1.1, height=size, dpi=300, compression = 'lzw')

# Clusters (resolution 0.4)
Idents(data) <- "integrated_snn_res.0.4"
head(Idents(data))
DimPlot(data, label=TRUE) 
p <- DimPlot(data, label=FALSE) 
ggsave("fig_gte_PC20r04_UMAP.tiff", plot = p, units="in", width=size*1.1, height=size*1, dpi=300, compression = 'lzw')

# Samples
Idents(data) <- "sampleCombined"
p <- DimPlot(data, label=FALSE, cols = samplePalette) 
ggsave("fig_gte_UMAP_samplesCombined.tiff", plot = p, units="in", width=size*1.2, height=size*1, dpi=300, compression = 'lzw')

# Cell Types
  # Move celltype labels to meta files
celltypeMeta <- read.csv("D:\\backup files\\getegbm\\gete-gbm\\results\\GBM-GSC neuroblastoma TE\\2022-11-07_celltypes_gbmscte\\gbmscte_meta_celltypes.csv", row.names = 1)
data@meta.data$int03_celltypes <- factor(celltypeMeta$int03_celltypes, levels = celltypes)
Idents(data) <- "int03_celltypes"
p <- DimPlot(data, label=FALSE, cols = celltypePalette) 
ggsave("fig_gte_UMAP_celltypes.tiff", plot = p, units="in", width=size*1.3, height=size*1, dpi=300, compression = 'lzw')

df <- data@meta.data %>% select(integrated_snn_res.0.3, int03_celltypes) %>% count(integrated_snn_res.0.3, int03_celltypes) 
write.csv(df, file="gte_celltypecounts.csv", row.names = F)

data@meta.data$int04_celltypes <- factor(celltypeMeta$int04_celltypes, levels = celltypes)
df <- data@meta.data %>% select(integrated_snn_res.0.4, ) %>% count(integrated_snn_res.0.3, int03_celltypes) 
write.csv(df, file="gte_celltypecounts.csv", row.names = F)

# GBM subtypes
data$gbm_subtype <- factor(data@meta.data$gbm_subtype, levels = gbmsubtypes, labels = gbmsubtypes_labels)
Idents(data) <- "gbm_subtype"
# data <- SetIdent(data, value = data@meta.data$gbm_subtype) 
p <- DimPlot(data, label=FALSE, cols = gbmPaletteGTE) 
ggsave("fig_gte_UMAP_gbmsubtypes.tiff", plot = p, units="in", width=size*1.1, height=size*1, dpi=300, compression = 'lzw')
```

## Dot Plots

```{r}
# Cell Types
Idents(data) <- "int03_celltypes"
features <- c(#"HBB", #Blood
              "CD3E", #"CD8A", #T-cells
              "FLT1", "VWF", "FN1", #Endothelial
              #"ASCL1", # IPC-late (?)
              #"PVALB", "SST", "GAD1", # Differentiated Cortical Interneurons (Inhibitory neurons)
              "MKI67", "MCM6", "TOP2A", "PCNA",  #Proliferating Cell Type
              "PTPRC", "C1QC", "CD68", "TREM2", "GPR34", "CSF1R", "CX3CR1", #Microglia, 
                #"P2RY12", "HEXB" were absent
              "MYRF", "MBP", "MOG", "PLP1", #Oligodendrocytes
              "OLIG1", "OLIG2", "PDGFRA", "SOX10",  #OPC, "COL20A1" was absent
              "GFAP", "AQP4", "HOPX", "SLC1A2" #Astrocytes
              #"HES1" #NPC
             )

p <- DotPlot(data, features = features) +   scale_colour_gradient2() + 
      xlab("Known Brain Cell Markers") + ylab("Cell Types") + coord_flip() + 
      labs(size = "% Expressed", color = "Avg Expression") +
      theme(axis.text.x = element_text(angle = 40, vjust = 1, hjust=1)) 
ggsave("fig_gte_dotplot_int03_celltypes_summary.tiff", plot = p, units="in", width=size*1.1, height=size*1.3, dpi=300, compression ='lzw')

# GBM subtypes (smaller size for the paper) - From summary ppt
# GSEA analysis 
# Gene Ontology
```

## Remove object from memory

```{r}
rm(data)
gc()
```

## End of Notebook

```{r Load-GE}
sessionInfo()
```
