---
title: "Healthy ASD Control Samples pre-filtered figures (GE)"
date: 2023-08-09
author: Samantha Yuen
output:
  html_document:
    toc: yes
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "./figs-ge/"
    )
  })
editor_options:
  chunk_output_type: inline
---

**Goal**: Optimizing formatting of figures for my thesis

## Load Libraries

```{r}
set.seed(100)

library(ggplot2)
library(SeuratObject)
library(Seurat)
library(ggbreak)
library(dplyr)

library(conflicted)
conflict_prefer("select", "dplyr") ## required in %>% dplyr

print(getwd())
size = 5

samplePalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#CC79A7", 
                   "#ff716e", "#999999", "#0072B2", "#194c76", "#D55E00", 
                   "#3a4f41", "#6699cc", "#713e5a")
    # "SRR9262920" "SRR9262922" "SRR9262923" "SRR9262932" "SRR9262937" 
    # "SRR9262938" "SRR9262946" "SRR9262956" "SRR9264382" "SRR9264383" 
    # "SRR9264385" "SRR9264388" "SRR9264389"


celltypePalette <- c("#E69F00", "#ff716e", "#CC79A7", "#56B4E9", "#009E73", "#0072B2", "#F0E442", "#A5B6AD")
celltypes <- c(
  "Astrocyte",
  "OPC",
  "Diff. Oligodendrocytes",
  "Microglia",
  "Proliferating",
  "Endothelial",
  "T-cell",
  "Intermediate")
```

## Load Data

```{r Load-GE}
data <- readRDS("D:\\backup files\\getegbm\\gete-gbm\\results\\GBMGSCTE3_Healthy\\2023-03-20_gbmgsc_healthy_raw\\ge_healthy_raw.rds") 
print(head(DefaultAssay(data)))
DefaultAssay(data) <- "RNA"

colnames(data@meta.data)

sampleIDs <- sort(unique(data$sampleID))
print(sampleIDs)

# Factor sample names
data$sampleID <- factor(data$sampleID, levels = sampleIDs)
```

## Quality Control figures

Compute Cell counts per sample before filtering

```{r}
df <- data@meta.data %>% select(sampleID) %>% count(sampleID) 
write.csv(df, file="healthy_ge_samplecounts.csv", row.names = F)
```

[ggbreak](https://www.frontiersin.org/articles/10.3389/fgene.2021.774846/full) was used to split bars in a bar graph.

```{r}
# Cell Count (Bar)
p <- data@meta.data %>%
    ggplot(aes(x=sampleID, fill=sampleID)) + 
    labs(fill="Samples") + labs(x = "", y = "Unfiltered Cell Count") +
    scale_fill_manual(values = samplePalette) +
    # scale_x_discrete(labels = sampleID) +
    # scale_fill_discrete(labels = sampleID) +
    geom_bar() +
    theme_classic() + scale_y_break(c(30000, 70000), scales = 0.1, ticklabels = c(70000)) +
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), axis.text = element_text(size=10), legend.position = "none")
p
ggsave("fig_ge_cellcount-bar.tiff", plot = p, units="in", width=size*1, height=size*0.6, dpi=300, compression = 'lzw')

## MitoRatio x UMI x Genes
p <- data@meta.data %>% 
    ggplot(aes(x=nCount_RNA, y=nFeature_RNA, color=mitoRatio)) + 
    geom_point() + 
    scale_colour_gradient(low = "gray90", high = "black") +
    stat_smooth(method=lm) +
    scale_x_log10() + 
    scale_y_log10() + 
    labs(x = "log10 UMI Detected per Cell", y = "log10 Genes Detected per Cell") +
    theme_classic() +
    geom_vline(xintercept = 1000, linetype = "dashed", colour = "red") +
    geom_hline(yintercept = 300, linetype = "dashed", colour = "red") +
    facet_wrap(~sampleID) + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), axis.title.y = element_text(size=11, hjust=0.5), 
          strip.background = element_blank(),
          panel.border = element_rect(fill = NA, colour = "black"))
p
ggsave("fig_healthy_ge_umigenemitoratio_intercepts.tiff", plot = p, units="in", width=size*1.5, height=size*1.5, dpi=300, compression = 'lzw')

## MitoRatio
p <- data@meta.data %>% 
  	ggplot(aes(color=sampleID, x=mitoRatio, fill=sampleID)) + 
  	geom_density(alpha = 0.2) + 
    scale_color_manual(values = samplePalette, name = "Sample") +
    scale_fill_manual(values = samplePalette, name = "Sample") +
    labs(x = "Mitochondrial Expression (%)", y = "Cell Density") +
  	theme_classic() + scale_x_break(c(0.25, 0.6), scales = 0.1, ticklabels = c(0.60)) +
    theme(axis.title.x = element_text(size=11, hjust=0.35)) +
  	geom_vline(xintercept = 0.2, linetype = "dashed", colour = "red")
p
ggsave("fig_healthy_ge_mitoratio_density_legend.tiff", plot = p, units="in", width=size*1.3, height=size*0.8, dpi=300, compression = 'lzw')
ggsave("fig_healthy_ge_mitoratio_density.tiff", plot = p, units="in", width=size*1.1, height=size*0.6, dpi=300, compression = 'lzw')

## Genes per UMI (Density plot)
p <- data@meta.data %>% 
  	ggplot(aes(color=sampleID, x=log10GenesPerUMI, fill=sampleID)) + 
  	geom_density(alpha = 0.2) + 
    scale_color_manual(values = samplePalette) +
    scale_fill_manual(values = samplePalette) +
  	theme_classic() +
    labs(x = "log10 Genes Detected per Cell", y = "Cell Density") +
  	geom_vline(xintercept = 0.8, linetype = "dashed", colour = "red")
p
ggsave("fig_healthy_ge_log10GenesUMI_density.tiff", plot = p, units="in", width=size*1.1, height=size*0.6, dpi=300, compression = 'lzw')

```

Remove object from memory

```{r}
rm(data)
gc()
```

```{r}
sessionInfo()
```
