---
title: "Hidden Markov Model for Retrotransposon-mapped datasets"
author: "Samantha Yuen"
date: "Wed May 18, 2022"
output: 
    html_document:
        toc: true
        toc-depth: 3
---

# Hidden Markov Model 

R version 4.0.2
Framework: msm

```{r message=FALSE, warning=FALSE, cache=TRUE, cache.comments=FALSE, collapse=TRUE }
#load libraries and scripts
.libPaths(c("/scratch/samkyy/gete-gbm/renv/library/R-4.0/x86_64-pc-linux-gnu",
            "/tmp/RtmpJsRC8Z/renv-system-library",
            .libPaths()))
.libPaths()

resultsPath <- "~/scratch/gete-gbm/results" # nolint
getwd()

library(Seurat)
library(Matrix)
library(ggplot2)
library(tidyverse)
library(msm)
source("~/scratch/gete-gbm/bin/util.R")
source("~/scratch/gete-gbm/bin/util_seurat.R")
source("~/scratch/gete-gbm/bin/util_viz.R")
```

Load the human-genome-mapped + retrotransposon-mapped dataset.

```{r message=FALSE, warning=FALSE, cache=TRUE, cache.comments=FALSE, collapse=TRUE }
## load dataset
#gbmsc.ge <- readRDS("~/projects/def-ytanaka/common/te-gbm_proj/analysis/ge_gbmscIntUmap-subtypes.rds")
gbmsc.gte <- readRDS("~/projects/def-ytanaka/common/te-gbm_proj/analysis/gte_gbmscIntUmap-subtypes.rds") 
```


